require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/fulfillments", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Fulfillment. As you add validations to Fulfillment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Fulfillment.create! valid_attributes
      get fulfillments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      fulfillment = Fulfillment.create! valid_attributes
      get fulfillment_url(fulfillment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_fulfillment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      fulfillment = Fulfillment.create! valid_attributes
      get edit_fulfillment_url(fulfillment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Fulfillment" do
        expect {
          post fulfillments_url, params: { fulfillment: valid_attributes }
        }.to change(Fulfillment, :count).by(1)
      end

      it "redirects to the created fulfillment" do
        post fulfillments_url, params: { fulfillment: valid_attributes }
        expect(response).to redirect_to(fulfillment_url(Fulfillment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Fulfillment" do
        expect {
          post fulfillments_url, params: { fulfillment: invalid_attributes }
        }.to change(Fulfillment, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post fulfillments_url, params: { fulfillment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested fulfillment" do
        fulfillment = Fulfillment.create! valid_attributes
        patch fulfillment_url(fulfillment), params: { fulfillment: new_attributes }
        fulfillment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the fulfillment" do
        fulfillment = Fulfillment.create! valid_attributes
        patch fulfillment_url(fulfillment), params: { fulfillment: new_attributes }
        fulfillment.reload
        expect(response).to redirect_to(fulfillment_url(fulfillment))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        fulfillment = Fulfillment.create! valid_attributes
        patch fulfillment_url(fulfillment), params: { fulfillment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested fulfillment" do
      fulfillment = Fulfillment.create! valid_attributes
      expect {
        delete fulfillment_url(fulfillment)
      }.to change(Fulfillment, :count).by(-1)
    end

    it "redirects to the fulfillments list" do
      fulfillment = Fulfillment.create! valid_attributes
      delete fulfillment_url(fulfillment)
      expect(response).to redirect_to(fulfillments_url)
    end
  end
end
