require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/greens", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Green. As you add validations to Green, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Green.create! valid_attributes
      get greens_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      green = Green.create! valid_attributes
      get green_url(green)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_green_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      green = Green.create! valid_attributes
      get edit_green_url(green)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Green" do
        expect {
          post greens_url, params: { green: valid_attributes }
        }.to change(Green, :count).by(1)
      end

      it "redirects to the created green" do
        post greens_url, params: { green: valid_attributes }
        expect(response).to redirect_to(green_url(Green.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Green" do
        expect {
          post greens_url, params: { green: invalid_attributes }
        }.to change(Green, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post greens_url, params: { green: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested green" do
        green = Green.create! valid_attributes
        patch green_url(green), params: { green: new_attributes }
        green.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the green" do
        green = Green.create! valid_attributes
        patch green_url(green), params: { green: new_attributes }
        green.reload
        expect(response).to redirect_to(green_url(green))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        green = Green.create! valid_attributes
        patch green_url(green), params: { green: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested green" do
      green = Green.create! valid_attributes
      expect {
        delete green_url(green)
      }.to change(Green, :count).by(-1)
    end

    it "redirects to the greens list" do
      green = Green.create! valid_attributes
      delete green_url(green)
      expect(response).to redirect_to(greens_url)
    end
  end
end
